services:
  bot:
    restart: always
    build:
      context: chatbot/
      dockerfile: Dockerfile
    image: tpu-practice-searcher-bot:latest
    container_name: tpu-practice-searcher-bot-container
    networks:
      - prod_net
    environment:
      DATABASE_URL: "postgres://notdefaultuser:notdefaultuserpassword@db:5432/db"
    depends_on:
      - db
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: tpu-practice-searcher:latest
    container_name: tpu-practice-searcher-container
    networks:
      - prod_net
    environment:
      JWT_SECRET_TOKEN: "JWT_SECRET_TOKEN"
      TELEGRAM_BOT_TOKEN: "7675767595:AAE1xhwh82krR72WnINHFYPGCshT4ZfYKVU"
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: "./tpu-practice-searcher"

  db:
    image: postgres:16.0
    container_name: postgres-container
    networks:
      - prod_net
    environment:
      - POSTGRES_USER=notdefaultuser
      - POSTGRES_PASSWORD=notdefaultuserpassword
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
volumes:
  postgres_data:
networks:
  prod_net: