services:
  devbot:
    restart: always
    build:
      context: chatbot/
      dockerfile: Dockerfile
    image: tpu-practice-searcher-bot:latest
    container_name: dev-tpu-practice-searcher-bot-container
    networks:
      - dev_net
    environment:
      DATABASE_URL: "postgres://notdefaultuser:notdefaultuserpassword@devdb:5432/devdb"
    depends_on:
      - devdb
  devbackend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: tpu-practice-searcher:latest
    container_name: dev-tpu-practice-searcher-container
    networks:
      - dev_net
    environment:
      JWT_SECRET_TOKEN: "JWT_SECRET_TOKEN"
      TELEGRAM_BOT_TOKEN: "7675767595:AAE1xhwh82krR72WnINHFYPGCshT4ZfYKVU"
    ports:
      - "8001:8000"
    depends_on:
      - devdb
    command: "./tpu-practice-searcher"

  devdb:
    image: postgres:16.0
    container_name: dev-postgres-container
    networks:
      - dev_net
    environment:
      - POSTGRES_USER=notdefaultuser
      - POSTGRES_PASSWORD=notdefaultuserpassword
      - POSTGRES_DB=devdb
    ports:
      - "5433:5432"
    volumes:
      - dev_postgres_data:/var/lib/postgresql/data
    restart: always
volumes:
  dev_postgres_data:
networks:
  dev_net: