services:
  backend:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    image: tpu-practice-searcher:latest
    container_name: tpu-practice-searcher-container
    environment:
      JWT_SECRET_TOKEN: "JWT_SECRET_TOKEN"
      TELEGRAM_BOT_TOKEN: "7988184499:AAFo-ojimnv_9n3TMlzKJEmHqNXrUdZ8Yds"
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: "./tpu-practice-searcher"

  db:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_USER=notdefaultuser
      - POSTGRES_PASSWORD=notdefaultuserpassword
      - POSTGRES_DB=db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always
volumes:
  ./data: